export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as Products } from './Products'
export { default as Settings } from './Settings'
export { default as Main } from './Main'
export { default as Login } from './Login'
export { default as Root } from './Root'
