export const STORAGE_GET_REQUEST = 'STORAGE_GET_REQUEST'
export const STORAGE_GET_SUCCESS = 'STORAGE_GET_SUCCESS'
export const STORAGE_GET_ERROR = 'STORAGE_GET_ERROR'

export const STORAGE_SET_REQUEST = 'STORAGE_SET_REQUEST'
export const STORAGE_SET_SUCCESS = 'STORAGE_SET_SUCCESS'
export const STORAGE_SET_ERROR = 'STORAGE_SET_ERROR'

export const STORAGE_REMOVE_REQUEST = 'STORAGE_REMOVE_REQUEST'
export const STORAGE_REMOVE_SUCCESS = 'STORAGE_REMOVE_SUCCESS'
export const STORAGE_REMOVE_ERROR = 'STORAGE_REMOVE_ERROR'

export const API_GET_REQUEST_REQUEST = 'API_GET_REQUEST_REQUEST'
export const API_GET_REQUEST_SUCCESS = 'API_GET_REQUEST_SUCCESS'
export const API_GET_REQUEST_ERROR = 'API_GET_REQUEST_ERROR'

export const AUTH_ISSUE_TOKEN_REQUEST = 'AUTH_ISSUE_TOKEN_REQUEST'
export const AUTH_ISSUE_TOKEN_SUCCESS = 'AUTH_ISSUE_TOKEN_SUCCESS'
export const AUTH_ISSUE_TOKEN_ERROR = 'AUTH_ISSUE_TOKEN_ERROR'

export const AUTH_REFRESH_TOKEN_REQUEST = 'AUTH_REFRESH_TOKEN_REQUEST'
export const AUTH_REFRESH_TOKEN_SUCCESS = 'AUTH_REFRESH_TOKEN_SUCCESS'
export const AUTH_REFRESH_TOKEN_ERROR = 'AUTH_REFRESH_TOKEN_ERROR'
