export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_SUCCESS = 'CONFIG_SUCCESS'
export const CONFIG_ERROR = 'CONFIG_ERROR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'

export const API_REQUEST_REQUEST = 'API_REQUEST_REQUEST'
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'

export const STORAGE_GET_REQUEST = 'STORAGE_GET_REQUEST'
export const STORAGE_GET_SUCCESS = 'STORAGE_GET_SUCCESS'
export const STORAGE_GET_ERROR = 'STORAGE_GET_ERROR'

export const STORAGE_SET_REQUEST = 'STORAGE_SET_REQUEST'
export const STORAGE_SET_SUCCESS = 'STORAGE_SET_SUCCESS'
export const STORAGE_SET_ERROR = 'STORAGE_SET_ERROR'

export const STORAGE_REMOVE_REQUEST = 'STORAGE_REMOVE_REQUEST'
export const STORAGE_REMOVE_SUCCESS = 'STORAGE_REMOVE_SUCCESS'
export const STORAGE_REMOVE_ERROR = 'STORAGE_REMOVE_ERROR'

export const AUTH_ISSUE_TOKEN_REQUEST = 'AUTH_ISSUE_TOKEN_REQUEST'
export const AUTH_ISSUE_TOKEN_SUCCESS = 'AUTH_ISSUE_TOKEN_SUCCESS'
export const AUTH_ISSUE_TOKEN_ERROR = 'AUTH_ISSUE_TOKEN_ERROR'

export const CLIENT_INIT_REQUEST = 'CLIENT_INIT_REQUEST'
export const CLIENT_INIT_SUCCESS = 'CLIENT_INIT_SUCCESS'
export const CLIENT_INIT_ERROR = 'CLIENT_INIT_ERROR'

export const CLIENT_ISSUE_TOKEN_REQUEST = 'CLIENT_ISSUE_TOKEN_REQUEST'
export const CLIENT_ISSUE_TOKEN_SUCCESS = 'CLIENT_ISSUE_TOKEN_SUCCESS'
export const CLIENT_ISSUE_TOKEN_ERROR = 'CLIENT_ISSUE_TOKEN_ERROR'
